config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations:      'users/registrations' }

  root to: 'gyms#index'
  get '/about',   to: 'pages#about'
  resources :users, only: [:show, :index, :destroy]
  resources :posts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :gyms,  only: [:show, :index, :edit, :update, :new, :create, :destroy] do
    resources :reviews, only: [:new, :create, :destroy]
  end

  # ヘルスチェック用のroutesを設定
  resources :health_check, only: [:index]
end

app/models/gym.rb
class Gym < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :passive_relationships, class_name: 'Relationship',
                                   foreign_key: 'favorite_gym_id',
                                   dependent: :destroy
  has_many :guest_users, through: :passive_relationships

  default_scope -> { order(updated_at: :desc) }
  has_one_attached :gym_image
  validate  :validate_gym_image
  validates :gym_name, presence: true, length: { maximum: 50 },
                       uniqueness: { case_sensitive: false }
  validates :details, length: { maximum: 500 }
  validates :prefecture, presence: true
  validates :address,    presence: true

  # アドレスから経度・緯度を取得
  geocoded_by :full_address
  after_validation :geocode, if: -> { :address_changed? || :prefecture_changed? }

  def full_address
    prefecture + address
  end

  # ジム画像のリサイズ
  def gym_image_resize(size)
    gym_image.variant(combine_options: {  resize: "#{size}>",
                                          extent: size,
                                          background: 'white',
                                          gravity: :center }).processed
  end

  private

    # アップロード画像について、3MB以下 かつ jpeg,pngファイルのみ許可
    def validate_gym_image
      return unless gym_image.attached?

      if gym_image.blob.byte_size > 3.megabytes
        gym_image.purge
        errors.add(:gym_image, 'エラー ファイルサイズは3MBが上限です')
      elsif !image_type?
        gym_image.purge
        errors.add(:gym_image, 'エラー JPEG,PNGファイルを指定ください')
      end
    end

    def image_type?
      %w[image/jpg image/jpeg image/png].include?(gym_image.blob.content_type)
    end
end

app/controllers/gyms_controller.rb
class GymsController < ApplicationController
  before_action :user_login?, only: [:new, :create, :edit, :update, :destroy]
  before_action :admin_user?, only: [:destroy]

  MAX_GYMS    = 9
  MAX_REVIEWS = 5

  def index
    @q    = Gym.ransack(params[:q])
    @gyms = @q.result.includes(gym_image_attachment: :blob).page(params[:page]).per(MAX_GYMS)
  end

  def show
    @gym = Gym.find(params[:id])
    @users   = @gym.guest_users.includes(image_attachment: :blob)
    @reviews = @gym.reviews.includes(user: [image_attachment: :blob])
                                           .page(params[:page]).per(MAX_REVIEWS)

    @grade       = Review.rating_average(@gym.id, :grade)
    @breadth     = Review.rating_average(@gym.id, :breadth)
    @wall_height = Review.rating_average(@gym.id, :wall_height)
    @congestion  = Review.rating_average(@gym.id, :congestion)
  end

  def new
    @gym = Gym.new
  end

  def create
    @gym = Gym.new(gym_params)
    if @gym.save
      flash[:success] = 'ジムが追加されました！'
      redirect_to gym_path(@gym)
    else
      render 'new'
    end
  end

  def edit
    @gym = Gym.find(params[:id])
  end

  def update
    @gym = Gym.find(params[:id])
    if @gym.update_attributes(gym_params)
      redirect_to gym_path(@gym)
    else
      render 'edit'
    end
  end

  def destroy
    Gym.find(params[:id]).destroy
    redirect_to root_path
  end

  private

    def gym_params
      params.require(:gym).permit(:gym_name, :details, :gym_image,
                                  :prefecture, :address, :latitude, :longitude)
    end
end

app/helpers/gyms_helper.rb
module GymsHelper
end

app/views/gyms/_gym_form.html.erb
<%= form_for(@gym, url: yield(:url)) do |f| %>

  <%= render "devise/shared/error_messages", resource: f.object %>

  <div class="field form-group">
    <%= f.label :ジム名 %>
    <%= f.text_field :gym_name, autofocus: true, class: "form-control",
                                                 autocomplete: "name" %>
  </div>

  <div class="field form-group">
    <%= f.label :都道府県 %>
    <%= f.collection_select :prefecture, JpPrefecture::Prefecture.all,
         :name, :name, {autocomplete: "on"}, {class: "custom-select"} %>
  </div>

  <div class="field form-group">
    <%= f.label :住所（市区町村以降） %>
    <%= f.text_field :address, class: "form-control",
                                                 autocomplete: "address" %>
  </div>

  <div class="field form-group">
    <%= f.label :備考 %>
    <%= f.text_area :details, class: "form-control",
                                                 autocomplete: "details" %>
  </div>

  <div class="field form-group">
    <%= f.label :ジム画像 %>
    <%= f.file_field :gym_image, class: "form-control-file" %>
  </div>

  <div class="actions form-group mb-2">
    <%= f.submit yield(:button_text), class: "btn-info form-control mb-2" %>
  </div>

<% end %>

app/views/gyms/_like.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :favorite_gym_id, @gym.id %></div>
  <%= f.submit "ホームジム登録", class: "btn btn-info ml-auto" %>
<% end %>

app/views/gyms/_unlike.html.erb
<%= form_for(current_user.active_relationships.find_by(favorite_gym_id: @gym.id),
            html: { method: :delete }) do |f| %>
  <%= f.submit "ホームジム解除", class: "btn btn-warning ml-auto" %>
<% end %>

app/views/gyms/edit.html.erb
<% provide(:title, "GYM EDIT") %>
<% provide(:url, gym_path) %>
<% provide(:button_text, "ジムを更新する") %>

<div class="py-5 bg-light mb-0">
  <div class="row justify-content-center align-items-center w-100">
    <div class="col-md-4 bg-white">
      <div class="form-group text-center mt-3">
        <h2>GYM EDIT</h2>
      </div>

      <div class="form-group text-center mt-3">
        <% if @gym.gym_image.attached? %>
          <%= image_tag @gym.gym_image_resize("300x200") %>
        <% else %>
          <%= image_tag("gym_image.jpg", :size => "300x200") %>
        <% end %>
      </div>

      <%= render 'gyms/gym_form' %>

    </div>
  </div>
</div>

app/views/gyms/index.html.erb
<% provide(:title, "GradeShare") %>
<section class="jumbotron jumbotron-fluid text-center mb-0">
  <div class="container">
    <h1 class="jumbotron-heading">Grade Share</h1>
    <p class="lead text-white">
      クライミングジムのレビュー＆クライマー向けコミュニティサービス
    </p>
    <p>
      <% if !user_signed_in? %>
        <a href="/users/sign_up" class="btn btn-info my-2">はじめる</a>
      <% end %>
    </p>
  </div>
</section>

<div class="py-5 bg-light mb-0">
  <div class="container">

    <div class="text-center">
      <h3><strong><i class="fas fa-dumbbell"></i> CLIMBING GYM</strong></h3>
    </div>
    <div class="mb-4">
      <%= search_form_for(@q, url:gyms_path) do |f| %>
        <div class="form-inline">
          <%= f.search_field :gym_name_cont,
                              class: "form-control col-md-3 ml-auto mr-sm-2",
                              placeholder: "ジムを検索..."  %>
          <%= button_tag type: "submit", name: nil,
                              class: "btn my-2 my-sm-0 btn-info search-btn" do %>
            <i class="fas fa-search"></i>
          <% end %>
        </div>
      <% end %>
    </div>

    <div class="row">
      <% @gyms.each do |gym| %>
        <div class="col-md-4">
          <div class="card mb-4 box-shadow">
            <% if gym.gym_image.attached? %>
              <%= link_to image_tag(gym.gym_image_resize("600x400"),
                                    class: "card-img-top"), gym_path(gym) %>
            <% else %>
              <%= link_to image_tag("gym_image.jpg",
                                    class: "card-img-top"), gym_path(gym) %>
            <% end %>
            <div class="card-body mt-0 pt-0">
              <p class="card-text text-info my-1 pb-0" >
                <small><i class="fas fa-map-pin"></i> <%= gym.prefecture %></small>
              </p>
              <p class="card-text">
                <strong><%= link_to gym.gym_name, gym_path(gym), class: "text-dark" %></strong>
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">member:<%= gym.passive_relationships.count %>  review:<%= gym.reviews.count %></small>
                <small class="text-muted">Last update:<%= gym.updated_at.in_time_zone('Tokyo').strftime("%Y/%m/%d") %></small>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <%= paginate @gyms %>

  </div>
</div>

app/views/gyms/new.html.erb
<% provide(:title, "GYM CREATE") %>
<% provide(:url, gyms_path) %>
<% provide(:button_text, "ジムを作成する") %>

<div class="py-5 bg-light mb-0">
  <div class="row justify-content-center align-items-center w-100">
    <div class="col-md-4 bg-white">
      <div class="form-group text-center mt-3">
        <h2>GYM CREATE</h2>
      </div>

      <%= render 'gyms/gym_form' %>

    </div>
  </div>
</div>

app/views/gyms/show.html.erb
<% provide(:title, @gym.gym_name) %>
<div class="py-5 bg-light mb-0">
  <div class="container">
    <div class="text-center mb-4">
      <h2><strong><%= @gym.gym_name %></strong></h2>
    </div>

    <div class="row mb-4 p-4">
      <div class="col-md-6 float-left">
        <% if @gym.gym_image.attached? %>
          <%= image_tag(@gym.gym_image_resize("500x333"),
                                              class:"img-responsive") %>
        <% else %>
          <%= image_tag("gym_image.jpg", :size => "500x333",
                                              class:"img-responsive") %>
        <% end %>
      </div>
      <div class="col-md-6 float-right">
        <div id="map" style='width: 100%; height: 333px;'></div>
      </div>
    </div>

    <div class="bg-white p-4 mb-4">
      <div><h4>DESCRIPTION</h4></div>
      <div><b>所在地</b></div>
      <p><%= @gym.prefecture + @gym.address %></p>
      <% if !(@gym.details.empty?) %>
        <div><b>備　考</b></div>
        <%= simple_format(h(@gym.details)) %>
      <% end %>
      <div class="text-right">
        <% if user_signed_in? %>
          <%= link_to edit_gym_path, class: 'btn btn-info' do %>
            <i class="fas fa-edit"></i><span>編集</span>
          <% end %>
          <% if  current_user.admin? %>
            <%= link_to @gym, method: :delete,
                                  data: { confirm: "ジムを削除しますか？" },
                                  class: 'btn btn-info' do %>
               <i class="fas fa-trash-alt"></i><span>ジム削除</span>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="bg-white p-4 mb-4">
      <div><h4>REVIEW SCORE</h4></div>
      <div class="row block-center text-center">
        <ul style="list-style:none;" class="col">
          <li><%= content_tag(:span, @grade, class: "score") %></li>
          <li>難易度</li>
        </ul>
        <ul style="list-style:none;" class="col">
          <li><%= content_tag(:span, @breadth, class: "score") %></li>
          <li>広さ</li>
        </ul>
        <ul style="list-style:none;" class="col">
          <li><%= content_tag(:span, @wall_height, class: "score") %></li>
          <li>壁の高さ</li>
        </ul>
        <ul style="list-style:none;" class="col">
          <li><%= content_tag(:span, @congestion, class: "score") %></li>
          <li>混雑度</li>
        </ul>
      </div>
      <div class="text-right"><small>※スコアは５段階評価の平均</small></div>
    </div>

    <div class="bg-white p-4 mb-4">
      <div><h4>MEMBERS</h4></div>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <% if user.image.attached? %>
               <%= link_to image_tag(user.user_image_resize("60x60")), user %>
            <% else %>
               <%= link_to image_tag("avatar_image.png", :size => "60x60"), user %>
            <% end %>
          <% end %>
        </div>
      <% end %>
      <% if user_signed_in? %>
        <div id="like_form" class="text-right mb-4">
          <% if current_user.favorite?(@gym) %>
            <%= render 'unlike' %>
          <% else %>
            <%= render 'like' %>
          <% end %>
        </div>
      <% end %>
    </div>

    <div class="bg-white p-4 mb-4">
      <div><h4>REVIEWS</h4></div>
      <ul class="reviews">
        <% @reviews.each do |review| %>
          <li class="row">
            <div class="col-md-2 float-left inline-block">
              <% if review.user.image.attached? %>
                <%= link_to image_tag(review.user.user_image_resize("60x60")),
                                                              review.user %>
              <% else %>
                <%= link_to image_tag("avatar_image.png", :size => "60x60"),
                                                              review.user %>
              <% end %>
              <p><b><%= review.user.name %></b></p>
            </div>
            <div class="col-md-10 inline-block">
              <div class="flex-container">
                <h5><b><%= review.title %></b></h5>
                <% if user_signed_in? %>
                  <% if current_user.id == review.user_id %>
                    <%= link_to  gym_review_path(@gym,review),
                                 method: :delete, class:"text-secondary",
                                 data: { confirm: "レビューを削除しますか？" } do %>
                      <i class="fas fa-trash-alt"></i>
                    <% end %>
                  <% end %>
                <% end %>
              </div>
              <%= simple_format(h(review.content)) %>
              <p class="text-right">
                <small>難易度：<%= review.grade %>　広さ：<%= review.breadth %>　壁の高さ：<%= review.wall_height %>　混雑度：<%= review.congestion %></small>
              </p>
            </div>
          </li>
        <% end %>
      </ul>
      <div class="text-right">
        <% if user_signed_in? %>
          <%= link_to new_gym_review_path(@gym), class: 'btn btn-info' do %>
            <i class="fas fa-edit"></i><span>レビューする</span>
          <% end %>
        <% end %>
      </div>
      <%= paginate @reviews %>
    </div>

  </div>
</div>


<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: { scrollwheel: false }, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers([
      {
        "lat": <%= @gym.latitude %>,
        "lng": <%= @gym.longitude %>,
        "infowindow": '<p><%= @gym.gym_name %></p><p><%= @gym.address %></p><p><%= link_to "Googleマップで見る" ,"https://maps.google.co.jp/maps?q=loc:#{@gym.latitude},#{@gym.longitude}&iwloc=J",target: "_blank" %></p>'
      }
    ]);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    handler.getMap().setZoom(17);
  });
</script>