config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations:      'users/registrations' }

  root to: 'gyms#index'
  get '/about',   to: 'pages#about'
  resources :users, only: [:show, :index, :destroy]
  resources :posts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :gyms,  only: [:show, :index, :edit, :update, :new, :create, :destroy] do
    resources :reviews, only: [:new, :create, :destroy]
  end

  # ヘルスチェック用のroutesを設定
  resources :health_check, only: [:index]
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :user_login?,  only: [:new, :create, :destroy]
  before_action :correct_user, only: :destroy

  def new
    @gym    = Gym.find(params[:gym_id])
    @review = @gym.reviews.new
  end

  def create
    @gym     = Gym.find(params[:gym_id])
    @review  = @gym.reviews.build(review_params)
    @review.user_id = current_user.id
    if @review.save
      flash[:success] = 'レビューが投稿されました！'
      redirect_to gym_path(@gym)
    else
      render 'new'
    end
  end

  def destroy
    @review.destroy
    redirect_back(fallback_location: root_path)
  end

  private

    def review_params
      params.require(:review).permit(:title, :content, :grade, :breadth, :wall_height, :congestion)
    end

    def correct_user
      @review = current_user.reviews.find_by(id: params[:id])
      redirect_to root_path if @review.nil?
    end
end

app/views/reviews/new.html.erb
<% provide(:title, "REVIEW") %>

<div class="py-5 bg-light mb-0 review-edit">
  <div class="row justify-content-center align-items-center w-100">
    <div class="col-md-4 bg-white">
      <div class="form-group text-center mt-3">
        <h2>REVIEW</h2>
      </div>

      <%= form_for(@review, url: gym_reviews_path) do |f| %>

        <%= render "devise/shared/error_messages", resource: f.object %>

        <div class="field form-group">
          <%= f.label :タイトル %>
          <%= f.text_field :title, autofocus: true, class: "form-control",
                                                    autocomplete: "title" %>
        </div>

        <div class="field form-group">
          <%= f.label :本文 %>
          <%= f.text_area :content, class: "form-control",
                                                    autocomplete: "content" %>
        </div>

        <div class="field form-group">
          <%= f.label :難易度 %>
          <%= f.select :grade, [["1(簡単)", 1], ["2(少し簡単)", 2],  ["3(標準的)", 3], ["4(少し難しい)", 4], ["5(難しい)", 5] ], {:selected => 3}, {class: "custom-select"} %>
        </div>

        <div class="field form-group">
          <%= f.label :広さ %>
          <%= f.select :breadth, [["1(狭い)", 1], ["2(少し狭い)", 2],  ["3(標準的)", 3], ["4(少し広い)", 4], ["5(広い)", 5] ], {:selected => 3}, {class: "custom-select"} %>
        </div>

        <div class="field form-group">
          <%= f.label :壁の高さ %>
          <%= f.select :wall_height, [["1(低い)", 1], ["2(少し低い)", 2],  ["3(標準的)", 3], ["4(少し高い)", 4], ["5(高い)", 5] ], {:selected => 3}, {class: "custom-select"} %>
        </div>

        <div class="field form-group">
          <%= f.label :混雑度 %>
          <%= f.select :congestion, [["1(空いている)", 1], ["2(少し空いている)", 2],  ["3(標準的)", 3], ["4(少し混んでいる)", 4], ["5(混んでいる)", 5] ], {:selected => 3}, {class: "custom-select"} %>
        </div>

        <div class="actions form-group mb-2">
          <%= f.submit "レビューを投稿する", class: "btn-info form-control mb-2" %>
        </div>
      <% end %>

    </div>
  </div>
</div>