config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations:      'users/registrations' }

  root to: 'gyms#index'
  get '/about',   to: 'pages#about'
  resources :users, only: [:show, :index, :destroy]
  resources :posts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :gyms,  only: [:show, :index, :edit, :update, :new, :create, :destroy] do
    resources :reviews, only: [:new, :create, :destroy]
  end

  # ヘルスチェック用のroutesを設定
  resources :health_check, only: [:index]
end

app/views/layouts/_footer.html.erb
<footer class="footer mt-0">
  <div class="col text-center">
    <small> © 2019 GradeShare.com</small>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" id=logo href="/" >Grade Share</a>
      <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber" aria-expanded="false" aria-label="ナビゲーションの切替">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="Navber">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to root_path, class: "nav-link" do %>
                <i class="fas fa-home fa-fw"></i>HOME
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to about_path, class: "nav-link" do %>
                <i class="fas fa-chalkboard-teacher fa-fw"></i>ABOUT
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to current_user, class: "nav-link" do %>
                <i class="far fa-comments fa-fw"></i>COMMENTS
              <% end %>
            </li>
            <li class="nav-item dropdown">
              <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <% if current_user.image.attached? %>
                  <%= image_tag current_user.user_image_resize("30x30") %> <b class="caret"></b>
                <% else %>
                  <%= image_tag("avatar_image.png", :size => "30x30") %> <b class="caret"></b>
                <% end %>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "ジム追加", new_gym_path, class:"dropdown-item" %>
                <%= link_to "ユーザー一覧", users_path, class:"dropdown-item" %>
                <%= link_to "設定", edit_user_registration_path, class:"dropdown-item" %>
                <div class="dropdown-divider"></div>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"dropdown-item" %></a>
              </div>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to root_path, class: "nav-link" do %>
                <i class="fas fa-home fa-fw"></i>HOME
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to about_path, class: "nav-link" do %>
                <i class="fas fa-chalkboard-teacher fa-fw"></i>ABOUT
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_registration_path, class: "nav-link" do %>
                <i class="fas fa-user-plus fa-fw"></i>SIGN UP
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_session_path, class: "nav-link" do %>
                <i class="fas fa-sign-in-alt fa-fw"></i>LOGIN
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
    <script src="//maps.google.com/maps/api/js?v=3.23&key=<%= Rails.application.credentials.google[:google_map_api_key] %>"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <% flash.each do |key, value| %>
      <% key = "info" if key == "notice" %>
      <% key = "danger"  if key == "alert" %>
      <%= content_tag :div, value, class: "alert alert-#{key} text-center mb-0" %>
    <% end %>

    <%= yield %>

    <%= render 'layouts/footer' %>
  </body>
</html>